### ISSUE TITLE
Show correct line numbers when errors occur

### ISSUE THREAD

**Issue by alexanderadam** [afaundez/jekyll-haml-markup#11]
It seems that `jekyll-haml-markup` seems to have [the same problem as `jekyll-haml`](https://github.com/samvincent/jekyll-haml/issues/13) and won't show the proper haml line when errors occur.
For instance for missing variables.

**Comment by afaundez** [comment]
@alexanderadam thanks for the feedback. I am going to check what I can get [here](https://github.com/afaundez/jekyll-haml-markup/blob/master/lib/jekyll/haml/markup/parser.rb#L14)

**Comment by alexanderadam** [comment]
IMHO it's not possible to get the information because [converters don't get anything except the content of the file](https://github.com/jekyll/jekyll/blob/1a03aafb81a50b755b6b906913858e5c06691de3/lib/jekyll/renderer.rb#L102).

I opened [a corresponding feature request for Jekyll](https://github.com/jekyll/jekyll/issues/8298) though.

**Comment by afaundez** [comment]
Sorry for the delay. @alexanderadam I don't know if there something else to do here without modifying Jekyll's behavior.
If you got and idea let me know or send a PR.
